#!/usr/bin/env python3
"""Build a Plan-A-style base directory from real WSClean dirty/PSF images.

The controlled Plan-A products use synthetic dirty images generated by direct
PSF convolution.  This utility instead stacks already-imaged WSClean dirty maps
and PSFs, then fits a per-frequency scalar normalization so that

    dirty_nu ~= gain_nu * PSF_nu (*) [PB_nu sky_true_nu] .

If no primary beam is supplied, PB_nu is set to one and the script reduces to the
older shift-invariant PSF diagnostic.  The fitted gain is folded into the output
PSF cube.  The downstream framework can then use dirty_obs, psf_cube, and the
optional beam_cube without using injected truth in the fit; injected truth is
used here only to put the WSClean dirty image and the sky-truth cube on a
consistent diagnostic scale.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
from astropy.io import fits

from build_planA_psf_dirty_dataset import _write_cube


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", type=Path, required=True)
    ap.add_argument("--freq-start-mhz", type=float, default=106.0)
    ap.add_argument("--freq-stop-mhz", type=float, default=121.0)
    ap.add_argument("--freq-step-mhz", type=float, default=0.1)
    ap.add_argument(
        "--image-root-pattern",
        default="data/sdc3_hpc/all_{freq:.2f}/image_natural",
        help="Directory pattern containing WSClean dirty/PSF products.",
    )
    ap.add_argument(
        "--sky-pattern",
        default="/data2/sdc3/simulation/skymap/osm_prepare/all_{freq:.2f}.fits",
        help="Foreground sky map pattern in K.",
    )
    ap.add_argument(
        "--eor-pattern",
        default="/data2/sdc3/simulation/skymap/eor/deltaTb_f{freq:.2f}_N2048_fov9.1.fits",
        help="EoR sky map pattern in K.",
    )
    ap.add_argument(
        "--osm-pattern",
        default="/data2/sdc3/simulation/skymap/osm_prepare/osm/all_{freq:.2f}.osm",
        help="OSM pattern used to infer the bright-source clipping level.",
    )
    ap.add_argument("--crop-size", type=int, default=1536, help="Central crop size in pixels. Use <=0 for full image.")
    ap.add_argument("--crop-center-x", type=int, default=None)
    ap.add_argument("--crop-center-y", type=int, default=None)
    ap.add_argument("--dtype", choices=("float64", "float32"), default="float64")
    ap.add_argument("--psf-peak-normalize", action="store_true", default=True)
    ap.add_argument("--no-psf-peak-normalize", dest="psf_peak_normalize", action="store_false")
    ap.add_argument(
        "--primary-beam-mode",
        choices=("none", "power", "amplitude"),
        default="none",
        help=(
            "Optional primary-beam factor applied to the sky before PSF convolution. "
            "'power' uses normalized 0.5*(beam0+beam15); 'amplitude' uses its square root."
        ),
    )
    ap.add_argument("--primary-beam0-pattern", default=None, help="FITS pattern for WSClean beam-0 maps.")
    ap.add_argument("--primary-beam15-pattern", default=None, help="FITS pattern for WSClean beam-15 maps.")
    ap.add_argument(
        "--primary-beam-reference-freq-mhz",
        type=float,
        default=None,
        help="If set, use this frequency in the PB path patterns for all channels.",
    )
    ap.add_argument(
        "--primary-beam-normalize",
        choices=("center", "max", "p99"),
        default="center",
        help="How to normalize the WSClean beam map before applying it.",
    )
    ap.add_argument(
        "--fit-demean",
        action="store_true",
        help="Remove spatial means before fitting the per-frequency dirty/model gain.",
    )
    ap.add_argument("--data-error", type=float, default=0.005)
    return ap.parse_args()


def _parse_freqs(start: float, stop: float, step: float) -> List[float]:
    if step <= 0.0:
        raise ValueError("--freq-step-mhz must be positive.")
    count = int(round((float(stop) - float(start)) / float(step))) + 1
    if count <= 0:
        raise ValueError("Empty frequency range.")
    return [round(float(start) + i * float(step), 2) for i in range(count)]


def _squeeze_wsclean_2d(data: np.ndarray) -> np.ndarray:
    out = data
    while out.ndim > 2 and out.shape[0] == 1:
        out = out[0]
    if out.ndim != 2:
        raise ValueError(f"Expected 2D WSClean product after squeezing, got {out.shape}")
    return np.asarray(out)


def _load_wsclean_2d(path: Path, dtype: np.dtype) -> Tuple[np.ndarray, fits.Header]:
    with fits.open(path, memmap=True) as hdul:
        arr = _squeeze_wsclean_2d(np.asarray(hdul[0].data))
        hdr = hdul[0].header.copy()
    return np.asarray(arr, dtype=dtype), hdr


def _load_2d(path: Path, dtype: np.dtype) -> np.ndarray:
    with fits.open(path, memmap=True) as hdul:
        arr = np.asarray(hdul[0].data)
    if arr.ndim != 2:
        raise ValueError(f"Expected 2D FITS image in {path}, got {arr.shape}")
    return np.asarray(arr, dtype=dtype)


def _format_freq_path(pattern: str, freq: float) -> Path:
    return Path(str(pattern).format(freq=float(freq)))


def _crop2d(arr: np.ndarray, *, size: int, center_x: Optional[int], center_y: Optional[int]) -> np.ndarray:
    if int(size) <= 0:
        return arr
    h, w = arr.shape
    size = int(size)
    cx = int(center_x) if center_x is not None else w // 2
    cy = int(center_y) if center_y is not None else h // 2
    half = size // 2
    x0 = cx - half
    y0 = cy - half
    if x0 < 0 or y0 < 0 or x0 + size > w or y0 + size > h:
        raise ValueError(f"Invalid crop size={size}, center=({cx},{cy}) for image shape {(h, w)}")
    return np.asarray(arr[y0 : y0 + size, x0 : x0 + size])


def _infer_osm_clip_max_k(path: Path) -> Optional[float]:
    try:
        with path.open("r", encoding="utf-8") as handle:
            for _ in range(128):
                line = handle.readline()
                if not line:
                    break
                if "Maximum I value" in line and "=" in line:
                    return float(line.split("=", 1)[1].split("[", 1)[0].strip())
    except Exception:
        return None
    return None


def _k_to_jypix(freq_mhz: float) -> float:
    k_b = 1.380649e-23
    c = 299792458.0
    pix_rad = (16.0 / 3600.0) * (np.pi / 180.0)
    omega_pix = pix_rad**2
    nu_hz = float(freq_mhz) * 1e6
    return float(2.0 * k_b * nu_hz**2 / c**2 * omega_pix / 1e-26)


def _fft_convolve2d(image: np.ndarray, psf: np.ndarray) -> np.ndarray:
    return np.fft.irfft2(
        np.fft.rfft2(image) * np.fft.rfft2(np.fft.ifftshift(psf)),
        s=image.shape,
    )


def _load_primary_beam(
    *,
    args: argparse.Namespace,
    freq: float,
    dtype: np.dtype,
    crop_size: int,
    center_x: Optional[int],
    center_y: Optional[int],
) -> Tuple[Optional[np.ndarray], Optional[Dict[str, Any]]]:
    if str(args.primary_beam_mode) == "none":
        return None, None
    if not args.primary_beam0_pattern or not args.primary_beam15_pattern:
        raise ValueError("--primary-beam0-pattern and --primary-beam15-pattern are required when PB mode is enabled.")

    pb_freq = float(args.primary_beam_reference_freq_mhz) if args.primary_beam_reference_freq_mhz is not None else float(freq)
    beam0_path = _format_freq_path(str(args.primary_beam0_pattern), pb_freq)
    beam15_path = _format_freq_path(str(args.primary_beam15_pattern), pb_freq)
    if not beam0_path.exists() or not beam15_path.exists():
        raise FileNotFoundError(f"Primary-beam maps not found for {pb_freq:.2f} MHz: {beam0_path}, {beam15_path}")

    beam0, _ = _load_wsclean_2d(beam0_path, dtype)
    beam15, _ = _load_wsclean_2d(beam15_path, dtype)
    beam0 = _crop2d(beam0, size=int(crop_size), center_x=center_x, center_y=center_y)
    beam15 = _crop2d(beam15, size=int(crop_size), center_x=center_x, center_y=center_y)
    power = np.clip(0.5 * (beam0 + beam15), 0.0, None).astype(np.float64, copy=False)
    if str(args.primary_beam_normalize) == "center":
        norm = float(power[power.shape[0] // 2, power.shape[1] // 2])
    elif str(args.primary_beam_normalize) == "max":
        norm = float(np.max(power))
    else:
        norm = float(np.percentile(power, 99.0))
    if norm <= 0.0 or not np.isfinite(norm):
        raise ValueError(f"Invalid primary-beam normalization at {freq:.2f} MHz: {norm}")
    power_norm = power / norm
    if str(args.primary_beam_mode) == "power":
        beam = power_norm
    elif str(args.primary_beam_mode) == "amplitude":
        beam = np.sqrt(np.clip(power_norm, 0.0, None))
    else:  # pragma: no cover - argparse enforces choices.
        raise ValueError(f"Unsupported primary-beam mode: {args.primary_beam_mode}")
    stats = {
        "freq_mhz": float(freq),
        "pb_freq_mhz": float(pb_freq),
        "beam0_path": str(beam0_path),
        "beam15_path": str(beam15_path),
        "mode": str(args.primary_beam_mode),
        "normalize": str(args.primary_beam_normalize),
        "normalization": norm,
        "min": float(np.min(beam)),
        "max": float(np.max(beam)),
        "median": float(np.median(beam)),
        "p01": float(np.percentile(beam, 1.0)),
        "p99": float(np.percentile(beam, 99.0)),
    }
    return np.asarray(beam, dtype=dtype), stats


def _fit_gain(dirty: np.ndarray, model: np.ndarray, *, demean: bool) -> Tuple[float, Dict[str, float]]:
    d = np.asarray(dirty, dtype=np.float64)
    m = np.asarray(model, dtype=np.float64)
    if demean:
        d = d - float(np.mean(d))
        m = m - float(np.mean(m))
    denom = float(np.sum(m * m))
    if denom <= 0.0 or not np.isfinite(denom):
        raise ValueError("Cannot fit normalization gain: model has zero or invalid norm.")
    gain = float(np.sum(d * m) / denom)
    pred = gain * np.asarray(model, dtype=np.float64)
    resid = np.asarray(dirty, dtype=np.float64) - pred
    dirty_rms = float(np.sqrt(np.mean(np.asarray(dirty, dtype=np.float64) ** 2)))
    resid_rms = float(np.sqrt(np.mean(resid * resid)))
    pred_rms = float(np.sqrt(np.mean(pred * pred)))
    corr = _corr(np.asarray(dirty, dtype=np.float64), pred)
    return gain, {
        "gain": gain,
        "dirty_rms": dirty_rms,
        "pred_rms": pred_rms,
        "resid_rms": resid_rms,
        "resid_over_dirty_rms": resid_rms / dirty_rms if dirty_rms > 0.0 else float("nan"),
        "corr": corr,
    }


def _corr(a: np.ndarray, b: np.ndarray) -> float:
    aa = np.asarray(a, dtype=np.float64).reshape(-1)
    bb = np.asarray(b, dtype=np.float64).reshape(-1)
    aa = aa - float(np.mean(aa))
    bb = bb - float(np.mean(bb))
    den = float(np.sqrt(np.sum(aa * aa) * np.sum(bb * bb)))
    if den <= 0.0 or not np.isfinite(den):
        return float("nan")
    return float(np.sum(aa * bb) / den)


def _summary_stats(cube: np.ndarray) -> Dict[str, float]:
    arr = np.asarray(cube, dtype=np.float64)
    return {
        "min": float(np.min(arr)),
        "max": float(np.max(arr)),
        "mean": float(np.mean(arr)),
        "rms": float(np.sqrt(np.mean(arr * arr))),
    }


def main() -> None:
    args = parse_args()
    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    dtype = np.dtype(np.float64 if args.dtype == "float64" else np.float32)
    freqs = _parse_freqs(args.freq_start_mhz, args.freq_stop_mhz, args.freq_step_mhz)

    first_dirty = Path(args.image_root_pattern.format(freq=freqs[0])) / f"all_{freqs[0]:.2f}-dirty.fits"
    dirty0, dirty_hdr0 = _load_wsclean_2d(first_dirty, dtype)
    crop0 = _crop2d(dirty0, size=int(args.crop_size), center_x=args.crop_center_x, center_y=args.crop_center_y)
    shape = (len(freqs), int(crop0.shape[0]), int(crop0.shape[1]))
    dirty_cube = np.empty(shape, dtype=dtype)
    psf_cube = np.empty(shape, dtype=dtype)
    fg_cube = np.empty(shape, dtype=dtype)
    eor_cube = np.empty(shape, dtype=dtype)
    beam_cube = np.empty(shape, dtype=dtype) if str(args.primary_beam_mode) != "none" else None

    clip_max = _infer_osm_clip_max_k(Path(args.osm_pattern.format(freq=freqs[0])))
    gain_rows: List[Dict[str, float]] = []
    beam_rows: List[Dict[str, Any]] = []
    for idx, freq in enumerate(freqs):
        img_dir = Path(args.image_root_pattern.format(freq=freq))
        prefix = f"all_{freq:.2f}"
        dirty, _ = _load_wsclean_2d(img_dir / f"{prefix}-dirty.fits", dtype)
        psf, _ = _load_wsclean_2d(img_dir / f"{prefix}-psf.fits", dtype)
        dirty = _crop2d(dirty, size=int(args.crop_size), center_x=args.crop_center_x, center_y=args.crop_center_y)
        psf = _crop2d(psf, size=int(args.crop_size), center_x=args.crop_center_x, center_y=args.crop_center_y)
        if args.psf_peak_normalize:
            peak = float(np.max(np.abs(psf)))
            if peak <= 0.0 or not np.isfinite(peak):
                raise ValueError(f"Invalid PSF peak at {freq:.2f} MHz: {peak}")
            psf = psf / peak

        fg_k = _load_2d(Path(args.sky_pattern.format(freq=freq)), dtype)
        eor_k = _load_2d(Path(args.eor_pattern.format(freq=freq)), dtype)
        fg_k = _crop2d(fg_k, size=int(args.crop_size), center_x=args.crop_center_x, center_y=args.crop_center_y)
        eor_k = _crop2d(eor_k, size=int(args.crop_size), center_x=args.crop_center_x, center_y=args.crop_center_y)
        if clip_max is not None and np.isfinite(clip_max):
            fg_k = np.clip(fg_k, 0.0, float(clip_max))
        sky_jypix = (fg_k + eor_k) * _k_to_jypix(freq)
        beam, beam_stats = _load_primary_beam(
            args=args,
            freq=freq,
            dtype=dtype,
            crop_size=int(args.crop_size),
            center_x=args.crop_center_x,
            center_y=args.crop_center_y,
        )
        if beam_stats is not None:
            beam_rows.append(beam_stats)
        apparent_sky = sky_jypix if beam is None else sky_jypix * beam
        conv_model = _fft_convolve2d(apparent_sky, psf)
        gain, gain_stats = _fit_gain(dirty, conv_model, demean=bool(args.fit_demean))

        dirty_cube[idx] = dirty
        psf_cube[idx] = psf * gain
        fg_cube[idx] = fg_k * _k_to_jypix(freq)
        eor_cube[idx] = eor_k * _k_to_jypix(freq)
        if beam_cube is not None:
            if beam is None:
                raise RuntimeError("Internal error: beam_cube allocated but no beam loaded.")
            beam_cube[idx] = beam
        gain_rows.append({"freq_mhz": float(freq), **gain_stats})
        if idx == 0 or (idx + 1) % 10 == 0 or idx + 1 == len(freqs):
            print(
                f"[{idx + 1:03d}/{len(freqs):03d}] {freq:.2f} MHz "
                f"gain={gain:.4e} corr={gain_stats['corr']:.3f} "
                f"resid/dirty={gain_stats['resid_over_dirty_rms']:.3f}",
                flush=True,
            )

    dirty_path = out_dir / "dirty_obs.fits"
    psf_path = out_dir / "psf_cube.fits"
    fg_path = out_dir / "fg_true_cube2_dropcluster.fits"
    eor_path = out_dir / "eor_true_cube2.fits"
    beam_path = out_dir / "beam_cube.fits" if beam_cube is not None else None
    _write_cube(dirty_path, dirty_cube, freq_start_mhz=freqs[0], freq_step_mhz=float(args.freq_step_mhz))
    _write_cube(psf_path, psf_cube, freq_start_mhz=freqs[0], freq_step_mhz=float(args.freq_step_mhz))
    _write_cube(fg_path, fg_cube, freq_start_mhz=freqs[0], freq_step_mhz=float(args.freq_step_mhz))
    _write_cube(eor_path, eor_cube, freq_start_mhz=freqs[0], freq_step_mhz=float(args.freq_step_mhz))
    if beam_path is not None:
        if beam_cube is None:
            raise RuntimeError("Internal error: beam_path set but beam_cube missing.")
        _write_cube(beam_path, beam_cube, freq_start_mhz=freqs[0], freq_step_mhz=float(args.freq_step_mhz))

    gain_corr = np.array([row["corr"] for row in gain_rows], dtype=np.float64)
    gain_resid = np.array([row["resid_over_dirty_rms"] for row in gain_rows], dtype=np.float64)
    manifest: Dict[str, Any] = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "script": str(Path(__file__).resolve()),
        "out_dir": str(out_dir),
        "freqs_mhz": freqs,
        "shape": [int(v) for v in shape],
        "dtype": str(dtype),
        "image_root_pattern": str(args.image_root_pattern),
        "sky_pattern": str(args.sky_pattern),
        "eor_pattern": str(args.eor_pattern),
        "osm_clip_max_k": float(clip_max) if clip_max is not None else None,
        "crop": {
            "size": int(args.crop_size),
            "center_x": int(args.crop_center_x) if args.crop_center_x is not None else int(dirty0.shape[1] // 2),
            "center_y": int(args.crop_center_y) if args.crop_center_y is not None else int(dirty0.shape[0] // 2),
        },
        "normalization": {
            "mode": "per_frequency_truth_forward_gain_folded_into_psf",
            "fit_demean": bool(args.fit_demean),
            "psf_peak_normalize_before_gain": bool(args.psf_peak_normalize),
            "primary_beam_mode": str(args.primary_beam_mode),
            "primary_beam_normalize": str(args.primary_beam_normalize),
            "primary_beam_reference_freq_mhz": (
                float(args.primary_beam_reference_freq_mhz)
                if args.primary_beam_reference_freq_mhz is not None
                else None
            ),
            "gain_median": float(np.median([row["gain"] for row in gain_rows])),
            "gain_min": float(np.min([row["gain"] for row in gain_rows])),
            "gain_max": float(np.max([row["gain"] for row in gain_rows])),
            "corr_median": float(np.nanmedian(gain_corr)),
            "corr_min": float(np.nanmin(gain_corr)),
            "corr_max": float(np.nanmax(gain_corr)),
            "resid_over_dirty_rms_median": float(np.nanmedian(gain_resid)),
            "resid_over_dirty_rms_min": float(np.nanmin(gain_resid)),
            "resid_over_dirty_rms_max": float(np.nanmax(gain_resid)),
        },
        "dirty_header_excerpt": {
            k: dirty_hdr0.get(k)
            for k in ("BUNIT", "BMAJ", "BMIN", "BPA", "CDELT1", "CDELT2", "CRPIX1", "CRPIX2")
            if k in dirty_hdr0
        },
        "outputs": {
            "dirty_obs": str(dirty_path),
            "psf_cube": str(psf_path),
            "beam_cube": str(beam_path) if beam_path is not None else None,
            "fg_true": str(fg_path),
            "eor_true": str(eor_path),
        },
        "cube_stats": {
            "dirty_obs": _summary_stats(dirty_cube),
            "psf_cube": _summary_stats(psf_cube),
            "beam_cube": _summary_stats(beam_cube) if beam_cube is not None else None,
            "fg_true": _summary_stats(fg_cube),
            "eor_true": _summary_stats(eor_cube),
        },
        "notes": [
            "These are WSClean dirty images, not controlled dirty images generated by direct convolution.",
            "The per-frequency gain uses injected truth only to normalize the diagnostic forward model.",
            "Downstream smooth-template fitting still uses only dirty_obs and psf_cube.",
        ],
    }
    (out_dir / "normalization_by_frequency.json").write_text(
        json.dumps(gain_rows, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    if beam_rows:
        (out_dir / "primary_beam_by_frequency.json").write_text(
            json.dumps(beam_rows, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
